#!/usr/bin/env python3
"""
=============================================================================
 Duang 私有版 授权自动化脚本 v2.0
 执行方法: python3 duang_license_auto.py
 功能: 自动修改 aTrust 设备授权为至尊永久版
 支持: 新机器无授权 / 已有授权机器 / 从云端恢复
=============================================================================

 使用方法:
   1. 普通执行（本地已有授权或空机器自动处理）:
      python3 duang_license_auto.py

   2. 从云端下载授权包后执行（推荐新机器使用）:
      python3 duang_license_auto.py --url https://raw.githubusercontent.com/Scu9277/atrust/main/duang-license-package.tar.gz

   3. 自毁模式（执行完删除自身）:
      python3 duang_license_auto.py --self-destruct

   4. 云端一键运行:
      curl -sL https://raw.githubusercontent.com/Scu9277/atrust/main/duang_license_auto.py | python3 - --self-destruct
"""

import json
import os
import subprocess
import sys
import time
import tarfile
import tempfile
import shutil
import re

# ============================================================
# 配置
# ============================================================
LICENSE_TYPE = "\u81f3\u5c0a"
CUSTOMER_NAME = "Duang\u79c1\u6709\u7248"
MAX_USERS = 999999
EXPIRE_YEAR_2200 = 7258118400
SERIAL_NUMBER = "DUANG-PRIVATE-CLOUD-999999"
CONTAINER_NAME = "sdp-console"
BACKUP_DIR = "/root/duang_license_backup"

PATHS = {
    "etcdctl": "/usr/local/bin/etcdctl",
    "lic_dir": "/app/.info/license/",
    "lic_file": "/app/.info/license/sf_license.lic",
    "lic_conf": "/app/.info/license/sf_license_conf.json",
    "auth_key": "/app/.info/app-secret/auth_encode.key",
    "auth_iv": "/app/.info/app-secret/auth_encode.iv",
    "fingerprint": "/app/.info/atrust_deivce_fingerprint.pub",
    "daemon_config": "/app/docker-app/sdp-license-confd/config/config.prod.json",
    "supervisor_ini": "/app/docker-app/sdp-license-confd/supervisord/sdp-license-confd.ini",
}

# ============================================================
# 工具函数
# ============================================================

def run(cmd, shell=True):
    r = subprocess.run(cmd, shell=shell, capture_output=True, text=True)
    return r.stdout.strip(), r.stderr.strip(), r.returncode

def log(msg):
    print(f"[+] {msg}")

def warn(msg):
    print(f"[!] {msg}")

def error(msg):
    print(f"[-] ERROR: {msg}")

# ============================================================
# 生成最小可用 .lic 文件
# ============================================================

def generate_minimal_lic():
    """
    生成一个最小的 .lic 文件，让 daemon 不会因为文件不存在而崩溃。
    这个文件没有有效签名，但 daemon 能解析其结构，不会 crash。
    """
    log("生成 .lic 文件...")
    content = """#############################################################################
#
#       Sangfor ATRUST_HYBRID License Key File
#       DO NOT EDIT THIS FILE!!
#
#############################################################################

[global]
vendor =                            SANGFOR TECHNOLOGIES INC.
licno =                             DUANG-CLOUD-999999
gatewayid =                         00000000
customer_name =                     DuangSiYun
license_type =                      test
license_date =                      2200-01-01 00:00:00
license_version =                   2.4.10
customer_company =                  duang
sflicense_version =                 1.0.0
trial_date =                        7258118400
minimum_version =                   2.2.16.2
active_modules =                    API_KEY, EMM, IPSEC, KYLIN_OS, MOBILE_APP_AUTO_WRAPPED, SDPC, UEM, UPDATE_SOFT, VASTBASE, VIRT_NET
validation =                        DUMMY_VALIDATION_SKIP_CHECK
licno_list =                        DUANG-CLOUD-999999
fingerprint =                       DUMMY_FINGERPRINT

[base]
users =                             999999

[UEM]
users =                             999999

[EMM]
users =                             999999

[UPDATE_SOFT]
enable =                            true

[IPSEC]
enable =                            true

[VIRT_NET]
enable =                            true

[MOBILE_APP_AUTO_WRAPPED]
enable =                            true

[API_KEY]
sn =                                DUMMY_API_KEY
"""
    os.makedirs(PATHS["lic_dir"], exist_ok=True)
    with open(PATHS["lic_file"], "w") as f:
        f.write(content)
    # Also write conf
    with open(PATHS["lic_conf"], "w") as f:
        f.write('{"sn": ""}')
    log(f".lic 文件已创建: {PATHS['lic_file']}")

# ============================================================
# 从云端下载授权包
# ============================================================

def download_package(url):
    log(f"从云端下载授权包...")
    tmp = f"/tmp/duang_pkg_{int(time.time())}.tar.gz"
    out, err, rc = run(f"curl -sLk -o {tmp} --connect-timeout 30 '{url}' 2>/dev/null")
    if rc != 0 or not os.path.exists(tmp) or os.path.getsize(tmp) == 0:
        out, err, rc = run(f"wget -q -O {tmp} '{url}' 2>/dev/null")
    if not os.path.exists(tmp) or os.path.getsize(tmp) == 0:
        error("下载授权包失败")
        return None
    log(f"下载成功 ({os.path.getsize(tmp)} bytes)")
    return tmp

def extract_and_install(tarball):
    """解压并安装授权包到系统"""
    log("安装授权包...")
    extract_dir = tempfile.mkdtemp(prefix="duang_")
    try:
        with tarfile.open(tarball, "r:gz") as tar:
            tar.extractall(extract_dir)
        
        # 找到实际内容目录
        base = extract_dir
        items = os.listdir(base)
        if len(items) == 1 and os.path.isdir(os.path.join(base, items[0])):
            base = os.path.join(base, items[0])
        
        # 复制 .lic 文件
        lic_src = os.path.join(base, "license", "sf_license.lic")
        if os.path.exists(lic_src):
            os.makedirs(PATHS["lic_dir"], exist_ok=True)
            shutil.copy2(lic_src, PATHS["lic_file"])
            log(f".lic 文件已安装")
        
        # 复制 conf
        conf_src = os.path.join(base, "license", "sf_license_conf.json")
        if os.path.exists(conf_src):
            shutil.copy2(conf_src, PATHS["lic_conf"])
        
        # 复制 auth keys
        for fname in ["auth_encode.key", "auth_encode.iv"]:
            src = os.path.join(base, "app-secret", fname)
            if os.path.exists(src):
                os.makedirs(os.path.dirname(PATHS["auth_key"]), exist_ok=True)
                shutil.copy2(src, os.path.join(os.path.dirname(PATHS["auth_key"]), fname))
        
        # 复制 fingerprint
        fp_src = os.path.join(base, "fingerprint", "atrust_deivce_fingerprint.pub")
        if os.path.exists(fp_src):
            shutil.copy2(fp_src, PATHS["fingerprint"])
        
        # 复制 daemon config
        dc_src = os.path.join(base, "config.prod.json")
        if os.path.exists(dc_src):
            shutil.copy2(dc_src, PATHS["daemon_config"])
            log(f"daemon 配置文件已安装")
        
        # 复制 etcd 数据（备用）
        etcd_src = os.path.join(base, "etcd_license.json")
        if os.path.exists(etcd_src):
            shutil.copy2(etcd_src, PATHS["lic_dir"] + "etcd_license.json")
        
        log("授权包安装完成")
        return True
    except Exception as e:
        error(f"安装授权包失败: {e}")
        return False
    finally:
        shutil.rmtree(extract_dir, ignore_errors=True)
        if tarball.startswith("/tmp/"):
            try: os.remove(tarball)
            except: pass

# ============================================================
# 容器操作
# ============================================================

def get_container():
    out, _, _ = run("docker ps --format '{{.ID}}' --filter name=" + CONTAINER_NAME)
    return out.strip()

def copy_config_to_container():
    """复制 daemon 配置到容器内"""
    cid = get_container()
    if not cid or not os.path.exists(PATHS["daemon_config"]):
        return False
    container_path = "/home/app/sdp-license-confd/config/config.prod.json"
    run(f"docker cp {PATHS['daemon_config']} {cid}:{container_path} 2>/dev/null")
    # 验证
    out, _, _ = run(f"docker exec {cid} python3 -c 'import json; print(json.load(open(\"{container_path}\")).get(\"checkLicenseInterval\"))' 2>/dev/null")
    if "999999999" in out:
        log("容器配置已更新")
        return True
    # 尝试直接用 shell 修改
    run(f"docker exec {cid} sh -c 'echo \"{{\\\"checkLicenseInterval\\\": 999999999}}\" > /tmp/merge.json' 2>/dev/null")
    # 用 Python 读取修改
    run(f"""docker exec {cid} python3 -c '
import json
c = json.load(open("{container_path}"))
c["checkLicenseInterval"] = 999999999
c["dailyDuration"] = 86400
json.dump(c, open("{container_path}", "w"), indent=4)
print("Container config patched")
' 2>/dev/null""")
    return True

def restart_license_services():
    """重启容器内 license 服务"""
    cid = get_container()
    if not cid:
        warn("未找到容器，跳过重启")
        return
    log("重启容器内 license 服务...")
    run(f"docker exec {cid} supervisorctl restart license-confd sf_license sf_license_rest 2>/dev/null")
    time.sleep(3)
    out, _, _ = run(f"docker exec {cid} supervisorctl status 2>/dev/null | grep -E 'license|sf_li'")
    for line in out.split("\n"):
        if line.strip():
            parts = line.split()
            name = parts[0] if parts else ""
            status = parts[1] if len(parts) > 1 else ""
            if status == "RUNNING":
                log(f"  {name}: {status}")
            else:
                warn(f"  {name}: {status}")

    # 检查端口
    out, _, _ = run(f"docker exec {cid} ss -tlnp 2>/dev/null | grep 50037")
    if out:
        log("daemon API 端口 50037 已监听")
    else:
        warn("daemon API 端口 50037 未监听，尝试再次重启")
        time.sleep(2)
        run(f"docker exec {cid} supervisorctl restart license-confd 2>/dev/null")
        time.sleep(3)
        out, _, _ = run(f"docker exec {cid} ss -tlnp 2>/dev/null | grep 50037")
        if out:
            log("daemon API 端口 50037 已监听")

# ============================================================
# 修改 daemon 配置（延长检查间隔）
# ============================================================

def fix_daemon_config():
    if not os.path.exists(PATHS["daemon_config"]):
        warn("daemon 配置文件不存在")
        return False
    try:
        with open(PATHS["daemon_config"]) as f:
            cfg = json.load(f)
        cfg["checkLicenseInterval"] = 999999999
        with open(PATHS["daemon_config"], "w") as f:
            json.dump(cfg, f, indent=4)
        log("daemon checkLicenseInterval 已设为 31年")
        copy_config_to_container()
        return True
    except Exception as e:
        warn(f"修改 daemon 配置失败: {e}")
        return False

# ============================================================
# 修改 etcd 授权数据
# ============================================================

def apply_etcd_license():
    log("修改 etcd 授权数据...")
    ETCD = PATHS["etcdctl"]
    
    out, err, rc = run(f"{ETCD} get /config/private/license/local --print-value-only")
    if rc != 0 or not out:
        error(f"读取 etcd 失败: {err}")
        return False
    
    try:
        data = json.loads(out)
    except:
        error("etcd 数据解析失败")
        return False
    
    L = data["license"]
    L["licenseType"] = LICENSE_TYPE
    L["customerName"] = CUSTOMER_NAME
    L["status"] = "activated"
    L["sn"] = SERIAL_NUMBER
    L["licno"] = "DUANG-CLOUD-999999"
    
    Y = EXPIRE_YEAR_2200
    for m in ["base","uem","emm","virtualNet","appWrap","omniscient","skyInspect"]:
        if m not in L: continue
        ke = m + "ExpireTime" if m != "base" else "baseExpireTime"
        ku = m + "IsUnlimited" if m != "base" else "baseIsUnlimited"
        L[m][ke] = Y; L[m][ku] = True
        for p in (L[m].get("parts") or []):
            p["expireTime"] = Y; p["isUnlimited"] = True; p["status"] = "activated"
            p["licType"] = LICENSE_TYPE
            if "users" in p: p["users"] = MAX_USERS
        if "users" in L[m]: L[m]["users"] = MAX_USERS
    
    for mod in ["ipsec","updateSoft","kylinOS","distributedCluster"]:
        if mod in L:
            L[mod][mod + "ExpireTime"] = Y
            L[mod]["status"] = "activated"
            if mod + "IsUnlimited" in L[mod]: L[mod][mod + "IsUnlimited"] = True
    
    M = data.get("module", {})
    for mn in M:
        for fn in M[mn]:
            f = M[mn][fn]
            f["status"] = "activated"; f["expireTime"] = Y; f["isUnlimited"] = True
            if "users" in f: f["users"] = MAX_USERS
            for p in (f.get("parts") or []):
                p["status"] = "activated"; p["expireTime"] = Y; p["isUnlimited"] = True
                p["licType"] = LICENSE_TYPE
                if "users" in p: p["users"] = MAX_USERS
    
    data["devDeadline"] = 99999
    
    json_str = json.dumps(data, ensure_ascii=False)
    run(f"{ETCD} put /config/private/license/local '{json_str}'")
    log("etcd 授权数据写入成功")
    return True

# ============================================================
# 验证
# ============================================================

def verify():
    out, _, _ = run(f"{PATHS['etcdctl']} get /config/private/license/local --print-value-only")
    if not out: return False
    try:
        d = json.loads(out)
        l = d["license"]
        b = l.get("base", {})
        ok = True
        print("\n" + "=" * 50)
        print("  授权验证结果")
        print("=" * 50)
        print(f"  授权类型: {l.get('licenseType')}")
        print(f"  客户名称: {l.get('customerName')}")
        print(f"  授权状态: {l.get('status')}")
        print(f"  基础用户: {b.get('users')}")
        print(f"  无限期: {b.get('baseIsUnlimited')}")
        print(f"  到期时间戳: {b.get('baseExpireTime')}")
        print("=" * 50)
        if l.get("licenseType") != LICENSE_TYPE: ok = False
        if b.get("baseIsUnlimited") != True: ok = False
        if b.get("users") != MAX_USERS: ok = False
        return ok
    except:
        return False

# ============================================================
# 自毁
# ============================================================

def self_destruct():
    log("执行自毁清理...")
    script = os.path.abspath(sys.argv[0])
    run("rm -f /root/duang-license-package.tar.gz /root/duang-license-full-*.tar.gz 2>/dev/null")
    run("rm -rf /root/duang_license_backup /root/duang-license-pack /tmp/duang_*.py /tmp/fix_*.py /tmp/check_*.py 2>/dev/null")
    run("crontab -l 2>/dev/null | grep -v duang_license | grep -v apply_license | crontab - 2>/dev/null")
    run("systemctl disable license-fix.service 2>/dev/null; rm -f /etc/systemd/system/license-fix.service 2>/dev/null; systemctl daemon-reload 2>/dev/null")
    run("history -c 2>/dev/null; cat /dev/null > ~/.bash_history 2>/dev/null; cat /dev/null > /root/.bash_history 2>/dev/null")
    if os.path.exists(script):
        cleaner = "/tmp/.cleaner.sh"
        with open(cleaner, "w") as f:
            f.write("#!/bin/bash\nsleep 1\nrm -f \"" + script + "\" 2>/dev/null\nrm -f /tmp/.cleaner.sh 2>/dev/null\nhistory -c 2>/dev/null\n")
        os.chmod(cleaner, 0o700)
        subprocess.Popen(["/bin/bash", cleaner], start_new_session=True)
    log("自毁完成，脚本已删除")

# ============================================================
# 主流程
# ============================================================

def main():
    print("\n" + "=" * 60)
    print("  Duang 授权自动化脚本 v2.0")
    print("  适用于 aTrust / PlatOS 系统")
    print("=" * 60)
    
    args = sys.argv[1:]
    self_destruct_mode = "--self-destruct" in args
    url = None
    
    for i, arg in enumerate(args):
        if arg.startswith("--url="):
            url = arg.split("=", 1)[1]
        elif arg == "--url" and i + 1 < len(args):
            url = args[i + 1]
    
    if "--collect-only" in args:
        run("echo 'collect mode not implemented in v2, use v1'")
        return
    
    # Step 1: 确保 .lic 文件存在
    if not os.path.exists(PATHS["lic_file"]):
        warn(".lic 文件不存在")
        if url:
            log("尝试从云端下载授权包...")
            pkg = download_package(url)
            if pkg:
                extract_and_install(pkg)
        if not os.path.exists(PATHS["lic_file"]):
            log("生成最小 .lic 文件...")
            generate_minimal_lic()
    else:
        log(f".lic 文件已存在: {PATHS['lic_file']}")
    
    # Step 2: 修改 daemon 配置
    fix_daemon_config()
    
    # Step 3: 修改 etcd 数据
    apply_etcd_license()
    
    # Step 4: 重启服务
    restart_license_services()
    
    # Step 5: 验证
    time.sleep(2)
    if verify():
        log("授权修改成功！请刷新 Web 页面查看")
    else:
        warn("授权验证有异常，请检查")
    
    # 自毁
    if self_destruct_mode:
        self_destruct()

if __name__ == "__main__":
    main()
